pipeline{
    agent any
    
    environment {
        dotnet ='C:\\Program Files (x86)\\dotnet\\'
        }
        
    triggers {
        pollSCM 'H * * * *'
    }

    stages{
        stage('Checkout') {
            steps {
                git branch: 'master',
                credentialsId: 'id.rsa', url: 'ssh://git@github.com:AdilRashidov/CountApi.git', 
     }
 }
        stage('Restore packages'){
            steps{
                bat "dotnet restore C:\\Users\\dell\\source\repos\\CountApi\\CountApi\\CountApi.csproj"
     }   
  }
        stage('Clean'){
            steps{
                bat "dotnet clean C:\\Users\\dell\\source\repos\\CountApi\\CountApi\\CountApi.csproj"
     }
   }
        stage('Build'){
            steps{
                bat "dotnet build C:\\Users\\dell\\source\repos\\CountApi\\CountApi\\CountApi.csproj --configuration Release"
    }
 }
 }
}